language: java

jdk:
  - oraclejdk8

before_install:
  - find . -type f -print0 | xargs -0 sed -i "s/DYNAMIC-SNAPSHOT/0.1.${TRAVIS_BUILD_NUMBER}-SNAPSHOT/g"
  - mkdir /tmp/dynamodb
  - curl -o dynamodb.tar.gz -L http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest
  - tar zxf dynamodb.tar.gz --directory /tmp/dynamodb
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &

install: "mvn install -Dmaven.javadoc.skip=true -B -V"

script: true
